version: "3.7"
services:

  php-fpm:
    image: webdevops/php-nginx-dev:8.1
    container_name: application
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - .:/app:cached
    ports:
      - "20965:80"

  database:
    image: mysql:8.0.28
    container_name: database
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_DATABASE: Beadando
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '8306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
